language: python
dist: trusty
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

# no python3-wx before bionic
# no pyqt5 before xenial
matrix:
  include:
    - python: "2.7_with_system_site_packages"
      dist: trusty
      env: DIST="trusty" PACKAGES="python-gtk2 python-wxgtk2.8 python-qt4    python-pyside              "  TESTS2="test_pygtk.py test_wx.py test_pyqt.py              "

    - python: "2.7_with_system_site_packages"
      dist: xenial
      env: DIST="xenial" PACKAGES="python-gtk2 python-wxgtk3.0 python-qt4    python-pyside  python-pyqt5"  TESTS2="test_pygtk.py test_wx.py test_pyqt.py test_pyqt5.py"

    - python: "3.4_with_system_site_packages"
      dist: trusty
      env: DIST="trusty" PACKAGES="                            python3-pyqt4                            "  TESTS2="                         test_pyqt.py              "

    - python: "3.5_with_system_site_packages"
      dist: xenial
      env: DIST="xenial" PACKAGES="                            python3-pyqt4                python3-pyqt5" TESTS2="                         test_pyqt.py  test_pyqt5.py"

    - python: 3.7
      dist: xenial
      env: DIST="xenial"

install:
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends -y python-dev xvfb x11-utils x11-apps
 - sudo apt-get install --no-install-recommends -y scrot imagemagick 
 - sudo apt-get install --no-install-recommends -y $(echo $PACKAGES)
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - TESTS1="easy test_scrot.py test_imagemagick.py"
 - nosetests -v --with-coverage --cover-package=pyscreenshot  $TESTS1 $TESTS2
  
after_success:
 - coveralls
