language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "2.7_with_system_site_packages"
 
install:
 - sudo apt-get install python-dev xvfb x11-utils x11-apps
 - sudo apt-get install scrot imagemagick 
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" ]; then sudo apt-get install python-qt4 python-pyside python-gtk2 python-wxgtk2.8; fi
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2_with_system_site_packages" ]; then sudo apt-get install python3-pyside python3-pyqt4; fi
 - pip install -r requirements-test.txt
 - pip install .
 - pip install coveralls

script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - TESTS="easy test_scrot.py test_imagemagick.py"
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" ]; then TESTS="$TESTS test_pyside.py test_pyqt.py test_wx.py test_pygtk.py"; fi
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2_with_system_site_packages" ]; then TESTS="$TESTS test_pyside.py test_pyqt.py"; fi
 - nosetests -v --with-coverage --cover-package=pyscreenshot  $TESTS
  
after_success:
 - coveralls
