language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
  - "3.6"
env: DISTR_PY="general"

matrix:
  include:
    - name: "2.7_trusty_with_system"
      python: "2.7_with_system_site_packages"
      dist: trusty
      env: DISTR_PY="trusty 2"

    - name: "2.7_xenial_with_system"
      python: "2.7_with_system_site_packages"
      dist: xenial
      env: DISTR_PY="xenial 2"

    - name: "3.5_xenial_with_system"
      python: "3.5_with_system_site_packages"
      dist: xenial
      env: DISTR_PY="xenial 3"

    - name: "3.6_bionic_with_system"
      python: "3.6_with_system_site_packages"
      dist: bionic
      env: DISTR_PY="bionic 3"  PIPINST="pyside2"

    - name: 3.7_xenial
      python: 3.7
      dist: xenial

    - name: 3.8_xenial
      python: 3.8
      dist: xenial

    - name: 2.7_bionic
      python: 2.7
      dist: bionic

    - name: 3.7_bionic
      python: 3.7
      dist: bionic

    - name: 3.8_bionic
      python: 3.8
      dist: bionic

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
      language: shell # 'language: python' is an error on Travis CI macOS
      env: PATH=/Users/travis/Library/Python/3.7/bin:$PATH PIPUSER=--user PIPINST="qtpy wxpython pyobjc-framework-Quartz pyobjc-framework-LaunchServices"

    # - name: "Python 3.8 on Windows"
    #   os: windows # Windows 10.0.17134 N/A Build 17134
    #   language: shell # 'language: python' is an error on Travis CI Windows
    #   before_install:
    #     - choco install python --version 3.8
    #     - python -m pip install --upgrade pip
    #   env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

      # python: "2.7_with_system_site_packages" on bionic doesn't exist
      # windows has no GUI

addons:
  apt:
    sources:
      - sourceline: "ppa:jan-simon/pqiv"
      - sourceline: "ppa:nilarimogard/webupd8"
    packages:
      - xvfb
      - scrot
      - maim
      - imagemagick
      - pqiv
      - x11-utils
  homebrew:
    update: true # TODO: check # https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/10
    packages:
      - wxmac
      - pyqt
      - pyside
      - pqiv

install:
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get install --no-install-recommends -y xvfb $(./tests/packages.sh ${TRAVIS_DIST} ${TRAVIS_PYTHON_VERSION:0:1} ); fi
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then PIP=pip; else PIP=pip3; fi
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then PYTHON=python; else PYTHON=python3; fi
  - if [ ${TRAVIS_OS_NAME} == "windows" ]; then PYTHON=python; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then PYTHON=/usr/local/opt/python/libexec/bin/python; fi
  - $PIP install $PIPUSER --upgrade -r requirements-test.txt
  - $PIP install $PIPUSER --upgrade . ${PIPINST}

script:
  - cd tests
  - $PYTHON -m pyscreenshot.check.versions
  - if [ ${TRAVIS_OS_NAME} == "osx" ];   then $PYTHON -m pyscreenshot.check.speedtest 2> /dev/null; fi
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then $PYTHON -m pyscreenshot.check.speedtest --virtual-display 2> /dev/null; fi
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then pytest -v . ; fi
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then xvfb-run -s "-br -screen 0 900x800x24" pytest -v . ; fi
